file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	http.sslcainfo=C:/Users/WongD7/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	core.autocrlf=true
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	core.fscache=true
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	core.symlinks=false
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	pull.rebase=false
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	credential.helper=manager
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Users/WongD7/AppData/Local/Programs/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/WongD7/.gitconfig	core.editor="C:\Users\WongD7\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
file:C:/Users/WongD7/.gitconfig	credential.helper=wincred
file:C:/Users/WongD7/.gitconfig	user.email=chuenlik@hotmail.com
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/daniel1014/my-first-static-web-app.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
